"use client";

import { useState } from "react";
import { LazyNook3D as Nook3D } from "./components/LazyNook3D";
import type { NookMotion } from "./components/Nook3D";

const taskSteps = [
  { title:"Open the connected Page workspace", detail:"Uses the integration you explicitly connect", risk:"Read" },
  { title:"Prepare name, category, and description", detail:"Creates a reviewable draft only", risk:"Draft" },
  { title:"Pause before publishing", detail:"Nothing changes until you approve", risk:"Approval" },
];

const nookTypes = [
  { name:"Orbit", color:"#617fff", pale:"#9db0ff", job:"Calm browser guide", note:"Best for forms, research, and step-by-step help." },
  { name:"Mochi", color:"#ff825f", pale:"#ffb49e", job:"Expressive creative partner", note:"Best for drafts, ideas, and content workflows." },
  { name:"Pip", color:"#47cfa9", pale:"#a2ead8", job:"Quiet organization scout", note:"Best for files, reminders, and tidy routines." },
];

export default function Home() {
  const [demoStep,setDemoStep]=useState(-1);
  const [motion,setMotion]=useState<NookMotion>("wave");
  const [approved,setApproved]=useState(false);

  function runDemo(){setApproved(false);setDemoStep(0);setMotion("think");window.setTimeout(()=>{setDemoStep(1);setMotion("walk")},850);window.setTimeout(()=>{setDemoStep(2);setMotion("listen")},1750)}
  function approve(){setApproved(true);setMotion("success");window.setTimeout(()=>{setDemoStep(-1);setMotion("idle")},2200)}

  return <main className="trend-shell">
    <nav className="trend-nav"><a className="trend-brand" href="#top"><span>›_</span>nook</a><div><a href="#task">How it works</a><a href="#nooks">Meet the Nooks</a><a href="/create">Wardrobe</a><a href="#safety">Safety</a><a href="#build">For creators</a></div><div className="trend-nav-actions"><a href="/auth/sign-in?next=/dashboard">Sign in</a><a className="trend-primary small" href="/create">Create my Nook</a></div></nav>

    <section className="trend-hero" id="top"><div className="trend-hero-copy"><span className="trend-kicker"><i/> A companion you can see, teach, and trust</span><h1>Meet the little agent who lives on your desktop.</h1><p>Give Nook a task. They’ll show their plan, work across the apps you connect, and stop before anything important changes.</p><div className="trend-actions"><a className="trend-primary" href="/create">Create my Nook <span>→</span></a><button onClick={runDemo}>Watch a supervised task <span>▶</span></button></div><div className="trend-proof"><span><b>Visible</b> task plans</span><span><b>Explicit</b> approvals</span><span><b>Readable</b> receipts</span></div></div>
      <div className="trend-room"><div className="trend-room-grid"/><div className="trend-room-window"><i/><i/></div><div className="trend-room-shelf"><i/><i/><i/></div><Nook3D name="Orbit" motion={motion} message={demoStep===2?"The draft is ready. You choose what happens next.":demoStep>=0?"I’m preparing a safe preview.":"Want to make something useful together?"}/><div className="trend-room-status"><i/><span><b>Orbit is here</b><small>Web control room · private preview</small></span></div></div>
    </section>

    <section className="trend-task" id="task"><div className="trend-section-heading"><span className="trend-kicker">ONE BELIEVABLE TASK</span><h2>Ask once. See every step.</h2><p>This demo prepares a Facebook Page draft. It never claims an external action happened when it did not.</p></div><div className="task-workbench"><div className="task-request"><span>YOUR REQUEST</span><h3>“Help me set up a Facebook Page for my new shop.”</h3><div className="task-app-chip"><i>f</i><span><b>Facebook Page assistance</b><small>Guided mode · official integration path</small></span></div><button onClick={runDemo}>{demoStep<0?"Run the walkthrough":"Restart walkthrough"} <span>→</span></button></div><div className="task-plan"><div className="task-plan-head"><div><span>ORBIT’S PLAN</span><h3>Three steps, one approval</h3></div><i className={demoStep>=0?"live":""}>{demoStep<0?"Ready":"In progress"}</i></div>{taskSteps.map((item,index)=><article className={index<=demoStep?"active":""} key={item.title}><span>{index<demoStep?"✓":index+1}</span><div><b>{item.title}</b><small>{item.detail}</small></div><em>{item.risk}</em></article>)}{demoStep===2&&!approved&&<div className="task-approval"><div><span>READY FOR YOUR DECISION</span><b>Publish one Page draft?</b><small>The displayed name, category, and description will be sent to Meta.</small></div><button onClick={()=>{setDemoStep(-1);setMotion("idle")}}>Cancel</button><button onClick={approve}>Approve preview</button></div>}{approved&&<div className="task-complete"><span>✓</span><div><b>Prototype receipt created</b><small>No external change was made in this web demo.</small></div></div>}</div></div></section>

    <section className="trend-nooks" id="nooks"><div className="trend-section-heading row"><div><span className="trend-kicker">MEET THE NOOKS</span><h2>Different characters. Different ways to help.</h2></div><p>These are distinct working styles and visual personalities—not the same bot with a color filter.</p></div><div className="trend-nook-grid">{nookTypes.map((nook,index)=><article key={nook.name}><div className="trend-nook-stage" style={{background:`radial-gradient(circle at 50% 40%, ${nook.pale}, ${nook.color})`}}><Nook3D compact name={nook.name} primary={nook.color} secondary={nook.pale} outfit={index===0?"hoodie":index===1?"varsity":"utility"} accessory={index===0?"star":index===1?"cap":"antenna"} draggable={false} motion={index===0?"idle":index===1?"wave":"think"}/></div><div className="trend-nook-copy"><span>0{index+1}</span><div><h3>{nook.name}</h3><b>{nook.job}</b><p>{nook.note}</p></div></div></article>)}</div><div className="trend-closet-strip"><div><span className="trend-kicker">THE CLOSET</span><h3>Shirts, pins, hats, palettes, and saved outfits.</h3><p>Cosmetics are cosmetic. Buying a shirt never changes what your Nook can access.</p></div><div className="closet-swatches"><span className="hoodie-swatch"/><span className="varsity-swatch"/><span className="vest-swatch"/><i>+12</i></div><a href="/create">Open the wardrobe <span>→</span></a></div></section>

    <section className="trend-boundary"><div className="boundary-copy"><span className="trend-kicker">HOW THE REAL PRODUCT WORKS</span><h2>The website is the control room. Nook Desktop brings the character to your screen.</h2><p>A browser page cannot safely walk across native apps or reuse your logged-in sessions. Production Nook uses a signed desktop runtime and narrowly permissioned browser extension.</p><a href="/dashboard">Open the control room <span>→</span></a></div><div className="boundary-diagram"><article><i>01</i><span><b>Nook Web</b><small>Identity, wardrobe, skills, tasks, approvals, receipts</small></span></article><em>↔</em><article><i>02</i><span><b>Agent runtime</b><small>Policy checks, task plans, integrations, durable workflows</small></span></article><em>↔</em><article><i>03</i><span><b>Nook Desktop</b><small>Signed local app, movement, device pairing, narrow permissions</small></span></article></div></section>

    <section className="trend-safety" id="safety"><div className="trend-section-heading"><span className="trend-kicker">CUTE DOESN’T MEAN CARELESS</span><h2>Serious boundaries, written in plain language.</h2></div><div className="safety-shelves"><article><span>◎</span><h3>See the plan</h3><p>Every task starts with steps, access scope, and a clear risk level.</p></article><article><span>✓</span><h3>Approve the effect</h3><p>Messages, posts, purchases, and account changes always stop for you.</p></article><article><span>↺</span><h3>Keep the receipt</h3><p>Review what was read, changed, approved, and whether it can be undone.</p></article><article><span>⊘</span><h3>Never share secrets</h3><p>Passwords and payment details stay on the provider’s own page.</p></article></div></section>

    <section className="trend-build" id="build"><div><span className="trend-kicker">CREATOR MARKETPLACE</span><h2>Build a character people want to keep around.</h2><p>Publish rig-validated Nooks, declarative skills, and cosmetic wardrobe pieces. Creator uploads are reviewed, immutable, and never execute arbitrary code.</p><div><a className="trend-primary" href="/dashboard">Preview Creator Studio <span>→</span></a><a href="/create">Read the rig through the product</a></div></div><aside><span>CREATOR CHECKLIST</span>{["Rig and animation validation","Capability and permission disclosure","Safety test scenarios","License, price, and support window","Human review before listing"].map((item,index)=><p key={item}><i>{index+1}</i>{item}<b>{index<2?"Ready":"Required"}</b></p>)}</aside></section>

    <section className="trend-final"><Nook3D compact name="Orbit" motion="wave" outfit="hoodie" accessory="star" draggable={false}/><div><span className="trend-kicker">START WITH THE CHARACTER</span><h2>Make a Nook you’ll want to work with.</h2><p>Customize first. Sign in when you’re ready to save.</p></div><a className="trend-primary" href="/create">Create my Nook <span>→</span></a></section>
    <footer className="trend-footer"><a className="trend-brand" href="#top"><span>›_</span>nook</a><p>A visible, teachable desktop companion—built with honest boundaries.</p><div><a href="#task">How it works</a><a href="/create">Wardrobe</a><a href="#safety">Safety</a><a href="#build">Creators</a><a href="/dashboard">Product preview</a></div><small>© 2026 Nook Labs · Private product prototype</small></footer>
  </main>;
}
